name: Air Quality Pipeline

on:
  schedule:
    # Run feature pipeline every hour
    - cron: "0 * * * *"
    # Run model retraining every day at midnight (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs from GitHub UI

jobs:
  feature_pipeline:
    if: github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Feature Pipeline
        run: python feature_pipeline.py

  model_retraining:
    if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Model Retraining
        run: python train_model.py
